#!/bin/bash

inputDirectory=$1
outputDirectory=$2

for xml in $inputDirectory/*.xml ; do 
	outputFile=$outputDirectory/`basename $xml .xml`.html
	xsltproc xslt/generateHtml.xslt $xml  > $outputFile
done 
