#!/bin/bash

inputDirectory=$1
outputDirectory=$2

for xml in $inputDirectory/*.xml ; do 
	outputFile=$outputDirectory/`basename $xml .xml`.gpx
	xsltproc xslt/generateGpx.xslt $xml > $outputFile 
done
